#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const project_root = path.resolve(__dirname, '..');

const pak = JSON.parse(
  fs.readFileSync(path.join(project_root, 'package.json'), 'utf8'),
);
const file = path.join(project_root, 'env.ts');
console.log(`📝 Generate the ${pak.name}@${pak.version} env file: ${file}`);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
// The user needs to manually fill in the necessary parameters.
export const appKey = '';
export const userId = '';
export const userToken = '';
export const targetId = '';
export const deviceIds = {
  fcm: '',
  huawei: '',
  honor: '',
  vivo: '',
  xiaomi: '',
  oppo: '',
  meizu: '',
  apns: '',
};
`;
if (fs.existsSync(file) === false) {
  fs.writeFileSync(file, content, 'utf-8');
}
